version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./src/staticfiles:/app/staticfiles
      - ./src/mediafiles:/app/mediafiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6

volumes:
  postgres_data:

